#dictionary for database pathway
database: 
  # db_path: "../data/score.db" 
  db_path: "/Users/shangweisong/Desktop/AIAP_Student_score/data/score.db"


#dictionary for ml models,change "enabled" to false to disable training of specific model
models:
  RandomForestRegressor:
    enabled: true
    params: 
      n_estimators: [50, 100, 200]
      max_depth: [None, 10, 20]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]

  LinearRegression:
    enabled: true 
    params: {} #not hyperparameters to tune
  SVR: 
    enabled: true
    params: 
      kernel: ['linear', 'poly', 'rbf']
      C: [0.1, 1, 10]
      gamma: ['scale', 'auto']
  XGBRegressor: 
    enabled: true
    params:
      n_estimators: [50, 100, 200]
      max_depth: [3, 5, 7]
      learning_rate: [0.01, 0.1, 0.2]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]

  LogisticRegression:
    enabled: false
    params: 
      penalty: ['l1', 'l2', 'elasticnet', 'none'] # Regularization
      C: [0.01, 0.1, 1, 10, 100]  # Inverse of regularization strength
      solver: ['lbfgs', 'liblinear', 'saga']  # Optimization algorithms
      max_iter: [100, 200, 500]  # Number of iterations
  
  KNeighborsClassifier:
    enabled: false
    params:
      n_neighbors: [3, 5, 7, 9, 11]  # Different values for k
      weights: ['uniform', 'distance']  # Weighting strategy
      metric: ['euclidean', 'manhattan', 'minkowski']  # Distance metrics

  nn_model:
    enabled: false
    params: 
      batch_size: [16, 32, 64]
      epochs: [10, 20, 50]
      optimizer: ['adam', 'rmsprop', 'sgd']
      init: ['glorot_uniform', 'he_normal', 'uniform']
      dropout_rate: [0.2, 0.3, 0.4]


preprocessing:
  drop_duplicates: true
  drop_na: true
  scale_numerical: true
  encode_categorical: true
  convert_bool: true

  pca:
    enabled: true
    variance_retained: 0.95

visualization:
  plot_r2_scores: true
  plot_residuals: true
  plot_predicted_vs_actual: true
  figure_size: [8, 6]
  color_scheme: skyblue